In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\satej\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\satej\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 1.7 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/11.5 MB 1.6 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/11.5 MB 1.6 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/11.5 MB 1.4 MB/s eta 0:00:08
   ----- ---------------------------------- 1.6/11.5 MB 1.4 MB/s eta 0:00:07
   ------- -------------------------------- 2.1/11.5 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.4/11.5 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.5 MB 1.5 MB/s eta 0:00:06
   ---------- ----------------------------- 3.1/11.5 MB 1.5 MB/s eta 0:00:06
   ------------ --------------------------- 3.7/11.5 MB 1.6 MB/s eta 0:00:05
   ------------- -------------------------- 3.9/11.5 MB 1.6 MB/s eta 0:00:05
   --------------- ------------------------ 4.5/11.5 MB 1.7 MB/s eta 0:00:05
   ----------------- ---------------------- 5.0/11.5 MB 1.7 MB/s eta 0:00:04
   ------------------ --------------------- 5.2/11.5 MB 1.7 MB/s eta 0:00:04
   -------------------- ------------------- 5.8/11.5 MB 1.8 MB/s eta 0:00:04
   --------------------- ------------------ 6.0/11.5 MB 1.8 MB/s eta 0:00:04
   --------------------- ------------------ 6.3/11.5 MB 1.8 MB/s eta 0:00:03
   ----------------------- ---------------- 6.8/11.5 MB 1.8 MB/s eta 0:00:03
   ------------------------- -------------- 7.3/11.5 MB 1.8 MB/s eta 0:00:03
   --------------------------- ------------ 7.9/11.5 MB 1.8 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.5 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 8.4/11.5 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 8.9/11.5 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 9.2/11.5 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 9.4/11.5 MB 1.8 MB/s eta 0:00:02
   --------------------------------- ------ 9.7/11.5 MB 1.8 MB/s eta 0:00:02
   ---------------------------------- ----- 10.0/11.5 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.5 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.5 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.5 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.5 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 1.6 MB/s eta 0:00:00
Downloading numpy-2.2.5-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 938.7 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/12.6 MB 1.2 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.6 MB 1.1 MB/s eta 0:00:11
   ---- ----------------------------------- 1.3/12.6 MB 1.1 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/12.6 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.6 MB 1.2 MB/s eta 0:00:10
   ------ --------------------------------- 2.1/12.6 MB 1.1 MB/s eta 0:00:10
   ------- -------------------------------- 2.4/12.6 MB 1.1 MB/s eta 0:00:09
   -------- ------------------------------- 2.6/12.6 MB 1.1 MB/s eta 0:00:09
   -------- ------------------------------- 2.6/12.6 MB 1.1 MB/s eta 0:00:09
   --------- ------------------------------ 2.9/12.6 MB 1.1 MB/s eta 0:00:09
   --------- ------------------------------ 3.1/12.6 MB 1.1 MB/s eta 0:00:09
   --------- ------------------------------ 3.1/12.6 MB 1.1 MB/s eta 0:00:09
   ---------- ----------------------------- 3.4/12.6 MB 1.1 MB/s eta 0:00:09
   ---------- ----------------------------- 3.4/12.6 MB 1.1 MB/s eta 0:00:09
   ----------- ---------------------------- 3.7/12.6 MB 991.3 kB/s eta 0:00:10
   ----------- ---------------------------- 3.7/12.6 MB 991.3 kB/s eta 0:00:10
   ------------ --------------------------- 3.9/12.6 MB 953.8 kB/s eta 0:00:10
   ------------ --------------------------- 3.9/12.6 MB 953.8 kB/s eta 0:00:10
   ------------- -------------------------- 4.2/12.6 MB 906.7 kB/s eta 0:00:10
   ------------- -------------------------- 4.2/12.6 MB 906.7 kB/s eta 0:00:10
   ------------- -------------------------- 4.2/12.6 MB 906.7 kB/s eta 0:00:10
   -------------- ------------------------- 4.5/12.6 MB 848.7 kB/s eta 0:00:10
   -------------- ------------------------- 4.5/12.6 MB 848.7 kB/s eta 0:00:10
   -------------- ------------------------- 4.5/12.6 MB 848.7 kB/s eta 0:00:10
   -------------- ------------------------- 4.7/12.6 MB 813.5 kB/s eta 0:00:10
   -------------- ------------------------- 4.7/12.6 MB 813.5 kB/s eta 0:00:10
   -------------- ------------------------- 4.7/12.6 MB 813.5 kB/s eta 0:00:10
   --------------- ------------------------ 5.0/12.6 MB 778.2 kB/s eta 0:00:10
   --------------- ------------------------ 5.0/12.6 MB 778.2 kB/s eta 0:00:10
   ---------------- ----------------------- 5.2/12.6 MB 751.8 kB/s eta 0:00:10
   ---------------- ----------------------- 5.2/12.6 MB 751.8 kB/s eta 0:00:10
   ---------------- ----------------------- 5.2/12.6 MB 751.8 kB/s eta 0:00:10
   ----------------- ---------------------- 5.5/12.6 MB 732.4 kB/s eta 0:00:10
   ----------------- ---------------------- 5.5/12.6 MB 732.4 kB/s eta 0:00:10
   ----------------- ---------------------- 5.5/12.6 MB 732.4 kB/s eta 0:00:10
   ----------------- ---------------------- 5.5/12.6 MB 732.4 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 689.0 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 689.0 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 689.0 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 689.0 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 689.0 kB/s eta 0:00:10
   ------------------- -------------------- 6.0/12.6 MB 641.8 kB/s eta 0:00:11
   ------------------- -------------------- 6.0/12.6 MB 641.8 kB/s eta 0:00:11
   ------------------- -------------------- 6.0/12.6 MB 641.8 kB/s eta 0:00:11
   ------------------- -------------------- 6.0/12.6 MB 641.8 kB/s eta 0:00:11
   ------------------- -------------------- 6.0/12.6 MB 641.8 kB/s eta 0:00:11
   ------------------- -------------------- 6.3/12.6 MB 603.3 kB/s eta 0:00:11
   ------------------- -------------------- 6.3/12.6 MB 603.3 kB/s eta 0:00:11
   ------------------- -------------------- 6.3/12.6 MB 603.3 kB/s eta 0:00:11
   ------------------- -------------------- 6.3/12.6 MB 603.3 kB/s eta 0:00:11
   ------------------- -------------------- 6.3/12.6 MB 603.3 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   -------------------- ------------------- 6.6/12.6 MB 571.6 kB/s eta 0:00:11
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   --------------------- ------------------ 6.8/12.6 MB 374.2 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ---------------------- ----------------- 7.1/12.6 MB 352.6 kB/s eta 0:00:16
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ----------------------- ---------------- 7.3/12.6 MB 329.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.6/12.6 MB 311.4 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------ --------------- 7.9/12.6 MB 293.2 kB/s eta 0:00:17
   ------------------------- -------------- 8.1/12.6 MB 282.6 kB/s eta 0:00:16
   ------------------------- -------------- 8.1/12.6 MB 282.6 kB/s eta 0:00:16
   ------------------------- -------------- 8.1/12.6 MB 282.6 kB/s eta 0:00:16
   ------------------------- -------------- 8.1/12.6 MB 282.6 kB/s eta 0:00:16
   ------------------------- -------------- 8.1/12.6 MB 282.6 kB/s eta 0:00:16
   ------------------------- -------------- 8.1/12.6 MB 282.6 kB/s eta 0:00:16
   ------------------------- -------------- 8.1/12.6 MB 282.6 kB/s eta 0:00:16
   ------------------------- -------------- 8.1/12.6 MB 282.6 kB/s eta 0:00:16
   -------------------------- ------------- 8.4/12.6 MB 277.1 kB/s eta 0:00:16
   -------------------------- ------------- 8.4/12.6 MB 277.1 kB/s eta 0:00:16
   -------------------------- ------------- 8.4/12.6 MB 277.1 kB/s eta 0:00:16
   -------------------------- ------------- 8.4/12.6 MB 277.1 kB/s eta 0:00:16
   -------------------------- ------------- 8.4/12.6 MB 277.1 kB/s eta 0:00:16
   -------------------------- ------------- 8.4/12.6 MB 277.1 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   --------------------------- ------------ 8.7/12.6 MB 253.4 kB/s eta 0:00:16
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ---------------------------- ----------- 8.9/12.6 MB 177.0 kB/s eta 0:00:22
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.2/12.6 MB 140.2 kB/s eta 0:00:25
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28
   ----------------------------- ---------- 9.4/12.6 MB 115.0 kB/s eta 0:00:28

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\satej\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [3]:
import pandas as pd

In [4]:
iris=pd.read_csv("iris.csv")

In [5]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
iris.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [8]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [9]:
iris.shape

(150, 6)

In [10]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [11]:
iris.columns.values

array(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
       'PetalWidthCm', 'Species'], dtype=object)

In [12]:
iris.describe(include="all")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,150.000000,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,Iris-setosa
freq,NaN,NaN,NaN,NaN,NaN,50
mean,75.500000,5.843333,3.054000,3.758667,1.198667,NaN
std,43.445368,0.828066,0.433594,1.764420,0.763161,NaN
min,1.000000,4.300000,2.000000,1.000000,0.100000,NaN
25%,38.250000,5.100000,2.800000,1.600000,0.300000,NaN
50%,75.500000,5.800000,3.000000,4.350000,1.300000,NaN
75%,112.750000,6.400000,3.300000,5.100000,1.800000,NaN
max,150.000000,7.900000,4.400000,6.900000,2.500000,NaN

In [13]:
iris['sepal.length']

KeyError: 'sepal.length'

In [14]:
iris['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [15]:
iris['PetalLengthCm']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: PetalLengthCm, Length: 150, dtype: float64

In [16]:
iris.sort_index(axis=1,ascending=False)

,Species,SepalWidthCm,SepalLengthCm,PetalWidthCm,PetalLengthCm,Id
0,Iris-setosa,3.5,5.1,0.2,1.4,1
1,Iris-setosa,3.0,4.9,0.2,1.4,2
2,Iris-setosa,3.2,4.7,0.2,1.3,3
3,Iris-setosa,3.1,4.6,0.2,1.5,4
4,Iris-setosa,3.6,5.0,0.2,1.4,5
...,...,...,...,...,...,...
145,Iris-virginica,3.0,6.7,2.3,5.2,146
146,Iris-virginica,2.5,6.3,1.9,5.0,147
147,Iris-virginica,3.0,6.5,2.0,5.2,148
148,Iris-virginica,3.4,6.2,2.3,5.4,149
149,Iris-virginica,3.0,5.9,1.8,5.1,150

In [17]:
iris.sort_values(by="SepalWidthCm")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor
119,120,6.0,2.2,5.0,1.5,Iris-virginica
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
...,...,...,...,...,...,...
5,6,5.4,3.9,1.7,0.4,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa

In [18]:
iris.iloc[5]

Id                         6
SepalLengthCm            5.4
SepalWidthCm             3.9
PetalLengthCm            1.7
PetalWidthCm             0.4
Species          Iris-setosa
Name: 5, dtype: object

In [19]:
iris[0:3]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [20]:
iris.loc[:, ["SepalLengthCm","SepalWidthCm"]]

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

In [21]:
iris.iloc[:5, :]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [22]:
iris.iloc[:, :4]

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0      1            5.1           3.5            1.4
1      2            4.9           3.0            1.4
2      3            4.7           3.2            1.3
3      4            4.6           3.1            1.5
4      5            5.0           3.6            1.4
..   ...            ...           ...            ...
145  146            6.7           3.0            5.2
146  147            6.3           2.5            5.0
147  148            6.5           3.0            5.2
148  149            6.2           3.4            5.4
149  150            5.9           3.0            5.1

[150 rows x 4 columns]

In [23]:
iris.iloc[:7, :5]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2
5   6            5.4           3.9            1.7           0.4
6   7            4.6           3.4            1.4           0.3

In [24]:
iris.iloc[3:5, 0:2]

   Id  SepalLengthCm
3   4            4.6
4   5            5.0

In [25]:
iris.iloc[[1, 2, 4],[0,2]]

   Id  SepalWidthCm
1   2           3.0
2   3           3.2
4   5           3.6

In [26]:
iris.iloc[1:3, :]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [27]:
iris.iloc[:, 1:3]

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

In [28]:
iris.iloc[1,1]

np.float64(4.9)

In [29]:
iris['petal.length'].iloc[5]

KeyError: 'petal.length'

In [30]:
iris['PetalLengthCm'].iloc[5]

np.float64(1.7)

In [31]:
cols_2_4=iris.columns[2:4]
 iris[cols_2_4]

IndentationError: unexpected indent (808338472.py, line 2)

In [32]:
cols_2_4=iris.columns[2:4]

In [33]:
cols_2_4=iris.columns[2:4]
 iris[cols_2_4]

IndentationError: unexpected indent (808338472.py, line 2)

In [34]:
cols_2_4=iris.columns[2:4]
 iris[cols_2_4]

IndentationError: unexpected indent (808338472.py, line 2)

In [35]:
cols_2_4=iris.columns[2:4]
iris[cols_2_4]

     SepalWidthCm  PetalLengthCm
0             3.5            1.4
1             3.0            1.4
2             3.2            1.3
3             3.1            1.5
4             3.6            1.4
..            ...            ...
145           3.0            5.2
146           2.5            5.0
147           3.0            5.2
148           3.4            5.4
149           3.0            5.1

[150 rows x 2 columns]

In [36]:
iris[iris.columns[2:4]].iloc[5:10]

   SepalWidthCm  PetalLengthCm
5           3.9            1.7
6           3.4            1.4
7           3.4            1.5
8           2.9            1.4
9           3.1            1.5

In [37]:
iris.isnull()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [38]:
data={'Name':['Jai','Princi','Gaurav','Anuj','Ravi','Natasha','Riya'],
 'Age':[17,17,18,17,18,17,17],
 'Gender':['M','F','M','M','M','F','F'],
 'Marks':[90,76,'NaN',74,65,'NaN',71]}

In [39]:
df=pd.DataFrame(data)

In [40]:
df

      Name  Age Gender Marks
0      Jai   17      M    90
1   Princi   17      F    76
2   Gaurav   18      M   NaN
3     Anuj   17      M    74
4     Ravi   18      M    65
5  Natasha   17      F   NaN
6     Riya   17      F    71

In [41]:
 c = avg = 0
 for ele in df['Marks']:
 if str(ele).isnumeric(): # Ensure 'ele' is numeric
 c += 1
 avg += float(ele) # Convert to float to avoid type issues
 avg /= c

IndentationError: expected an indented block after 'for' statement on line 2 (1621713844.py, line 3)

In [42]:
 c = avg = 0
 for ele in df['Marks']:
     if str(ele).isnumeric(): # Ensure 'ele' is numeric
         c += 1
         avg += float(ele) # Convert to float to avoid type issues
 avg /= c

In [43]:
df=df.replace(to_replace="NaN", value=avg)

C:\Users\satej\AppData\Local\Temp\ipykernel_26796\4092092248.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace(to_replace="NaN", value=avg)

In [44]:
import numpy as np
df = df.replace(to_replace=np.nan, value=avg)

In [45]:
df

      Name  Age Gender  Marks
0      Jai   17      M   90.0
1   Princi   17      F   76.0
2   Gaurav   18      M   75.2
3     Anuj   17      M   74.0
4     Ravi   18      M   65.0
5  Natasha   17      F   75.2
6     Riya   17      F   71.0

In [46]:
df['Gender'] = df['Gender'].map({'M': 0,'F': 1, }).astype(float)

In [47]:
df

      Name  Age  Gender  Marks
0      Jai   17     0.0   90.0
1   Princi   17     1.0   76.0
2   Gaurav   18     0.0   75.2
3     Anuj   17     0.0   74.0
4     Ravi   18     0.0   65.0
5  Natasha   17     1.0   75.2
6     Riya   17     1.0   71.0

In [48]:
df = df[df['Marks'] >= 75]

In [49]:
df = df.drop(['Age'], axis=1)

In [50]:
df

      Name  Gender  Marks
0      Jai     0.0   90.0
1   Princi     1.0   76.0
2   Gaurav     0.0   75.2
5  Natasha     1.0   75.2